alias dmgo='docker-machine start'
alias dmend='docker-machine stop'
alias fiitlog='ssh -c aes192-cbc -oHostKeyAlgorithms=ssh-dss holy17@student.fiit.stuba.sk'
alias winbash='/c/windows/System32/bash.exe'
alias npm='npm.cmd'
